language: cpp

cache:
  ccache: true

os:
  - linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-graph-dev
      - libboost-iostreams-dev
      - libcgal-dev
      - libcgal-qt5-dev
      - libgtest-dev
      - googletest
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - qtbase5-dev

env:
  global:
    - MAKEFLAGS="-j 2"

compiler:
  - clang
  - gcc

script:
 - cmake .
 - make
